--- #YAML:1.0
name:                Net-CIDR-Lookup
version:             0.3
abstract:            ~
license:             perl
author:              
    - Matthias Bethke <matthias@towiski.de>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::Class:                   0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
